<?php
/**
 * System Information and Test Page
 */

echo "<h2>System Information</h2>";

// PHP Version
echo "<p><strong>PHP Version:</strong> " . phpversion() . "</p>";

// Check if required extensions are loaded
$required_extensions = ['mysqli', 'curl', 'openssl'];
echo "<h3>Required Extensions:</h3>";
foreach ($required_extensions as $ext) {
    if (extension_loaded($ext)) {
        echo "✅ $ext loaded<br>";
    } else {
        echo "❌ $ext NOT loaded<br>";
    }
}

// Check file permissions
echo "<h3>File System Check:</h3>";
$dirs_to_check = [
    '../logs/',
    '../vendor/',
    '../vendor/phpmailer/',
    '../vendor/phpmailer/phpmailer/src/'
];

foreach ($dirs_to_check as $dir) {
    if (is_dir($dir)) {
        echo "✅ Directory exists: $dir<br>";
        if (is_writable($dir)) {
            echo "✅ Directory writable: $dir<br>";
        } else {
            echo "⚠️ Directory not writable: $dir<br>";
        }
    } else {
        echo "❌ Directory missing: $dir<br>";
    }
}

// Test database connection
echo "<h3>Database Connection Test:</h3>";
try {
    require_once '../config/database.php';
    $db = new Database();
    echo "✅ Database connection successful<br>";
    
    // Test users table
    $result = $db->query("SHOW TABLES LIKE 'users'");
    if ($result->num_rows > 0) {
        echo "✅ Users table exists<br>";
        
        // Count users
        $count_result = $db->query("SELECT COUNT(*) as count FROM users");
        $count = $count_result->fetch_assoc()['count'];
        echo "ℹ️ Total users in database: $count<br>";
    } else {
        echo "❌ Users table not found<br>";
    }
} catch (Exception $e) {
    echo "❌ Database error: " . $e->getMessage() . "<br>";
}

// Test email configuration
echo "<h3>Email Configuration Test:</h3>";
try {
    require_once '../config/email.php';
    echo "✅ Email configuration loaded<br>";
    
    // Check PHPMailer availability
    global $phpmailer_available;
    if ($phpmailer_available && class_exists('\PHPMailer\PHPMailer\PHPMailer')) {
        echo "✅ PHPMailer class available<br>";
        
        // Test creating instance
        $mail = new \PHPMailer\PHPMailer\PHPMailer(true);
        echo "✅ PHPMailer instance created<br>";
    } else {
        echo "⚠️ PHPMailer not available - using fallback logging<br>";
    }
    
} catch (Exception $e) {
    echo "❌ Email configuration error: " . $e->getMessage() . "<br>";
}

// Show current configuration
echo "<h3>Current Configuration:</h3>";
echo "<p>Document Root: " . $_SERVER['DOCUMENT_ROOT'] . "</p>";
echo "<p>Script Path: " . __FILE__ . "</p>";
echo "<p>Current Working Directory: " . getcwd() . "</p>";

// Test links
echo "<h3>Test Links:</h3>";
echo "<p><a href='email-diagnostic.php' target='_blank'>Email Diagnostic</a></p>";
echo "<p><a href='test-email.php' target='_blank'>Test Email Form</a></p>";
echo "<p><a href='forgot-password.php' target='_blank'>Forgot Password</a></p>";
echo "<p><a href='../admin/login.php' target='_blank'>Admin Login</a></p>";

?>
<!DOCTYPE html>
<html>
<head>
    <title>System Test - GASC Blood Bridge</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; line-height: 1.6; }
        h2, h3 { color: #dc2626; }
        .success { color: green; }
        .error { color: red; }
        .warning { color: orange; }
    </style>
</head>
<body>
    <!-- Content is generated by PHP above -->
</body>
</html>
